title: TTI Information Security Office
email: iso@tti.tamu.edu

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - createData.py
   - SearchResults.xml
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/

plugins:
 #- jekyll-sitemap
